-- ============================================================
-- Tgora OS — CRM Data Model Completion (Sprint CRM-2)
-- Safe to run multiple times (idempotent).
--
-- Context: Sprint CRM-1 (architecture-only, no code/schema changes) decided
-- the canonical sales pipeline: Company -> Contact -> Lead -> Deal -> Won ->
-- Project. Deal is the single commercial pipeline object; Lead is a
-- qualification-only record. This migration adds the minimum columns/table
-- needed to let Deal actually carry that responsibility:
--   - crm_deals.lead_id             (optional provenance link back to Lead)
--   - crm_deals.service_type_id     (which service this Deal is for)
--   - crm_deals.probability         (0-100, weighted-pipeline input)
--   - crm_deals.expected_close_date (added defensively via IF NOT EXISTS —
--                                     this column already exists in the app
--                                     today; kept here so this migration is
--                                     safe to run standalone on any database)
--   - crm_service_types             (new lookup table for service
--                                     classification, seeded with the
--                                     business's current service lines)
--
-- This migration does NOT:
--   - remove/rename any existing column
--   - remove any existing crm_leads status value or crm_deals stage value
--   - create/alter anything in Projects, Tasks, Finance, or Accounting
--   - add any trigger/automation
-- ============================================================

CREATE TABLE IF NOT EXISTS crm_service_types (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  service_key  text NOT NULL UNIQUE,
  service_name text NOT NULL,
  description  text NULL,
  is_active    boolean NOT NULL DEFAULT true,
  sort_order   integer NOT NULL DEFAULT 0,
  created_at   timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS crm_service_types_service_key_idx ON crm_service_types(service_key);
CREATE INDEX IF NOT EXISTS crm_service_types_is_active_idx   ON crm_service_types(is_active);

-- Seed: the business's current service lines. ON CONFLICT on the unique
-- service_key keeps this safe to re-run and safe to extend with more rows
-- later (new services can simply be INSERTed — no code change required).
INSERT INTO crm_service_types (service_key, service_name, sort_order) VALUES
  ('branding',          'Branding',          10),
  ('digital_marketing', 'Digital Marketing', 20),
  ('website',           'Website',           30),
  ('video_production',  'Video Production',  40),
  ('photography',       'Photography',       50),
  ('motion_graphics',   'Motion Graphics',   60),
  ('printing',          'Printing',          70),
  ('consulting',        'Consulting',        80)
ON CONFLICT (service_key) DO NOTHING;

-- crm_deals: additive columns only. All nullable — no existing row is
-- affected, no existing Deal becomes invalid.
ALTER TABLE crm_deals ADD COLUMN IF NOT EXISTS lead_id bigint NULL REFERENCES crm_leads(id);
ALTER TABLE crm_deals ADD COLUMN IF NOT EXISTS service_type_id bigint NULL REFERENCES crm_service_types(id);
ALTER TABLE crm_deals ADD COLUMN IF NOT EXISTS probability integer NULL;
ALTER TABLE crm_deals ADD COLUMN IF NOT EXISTS expected_close_date date NULL;

-- Guard the probability range without breaking existing NULL values.
-- (NOT VALID + separate VALIDATE keeps this safe/fast even on a large,
-- already-populated crm_deals table — matches the deferred-validation
-- pattern used elsewhere in this codebase for additive constraints.)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'crm_deals_probability_range_chk'
  ) THEN
    ALTER TABLE crm_deals
      ADD CONSTRAINT crm_deals_probability_range_chk
      CHECK (probability IS NULL OR (probability >= 0 AND probability <= 100))
      NOT VALID;
    ALTER TABLE crm_deals VALIDATE CONSTRAINT crm_deals_probability_range_chk;
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS crm_deals_lead_id_idx             ON crm_deals(lead_id);
CREATE INDEX IF NOT EXISTS crm_deals_service_type_id_idx     ON crm_deals(service_type_id);
CREATE INDEX IF NOT EXISTS crm_deals_probability_idx         ON crm_deals(probability);
CREATE INDEX IF NOT EXISTS crm_deals_expected_close_date_idx ON crm_deals(expected_close_date);

-- Force PostgREST to reload its schema cache immediately.
NOTIFY pgrst, 'reload schema';
