-- ============================================================
-- Tgora OS — Chart of Accounts Foundation (Sprint 4.3B)
-- Run AFTER finance_migration.sql (Sprint 4.0 — finance_accounts)
-- Safe to run multiple times (idempotent).
--
-- Purpose: lay the accounting-side foundation (Assets/Liabilities/Equity/
-- Revenue/Expense) that a future Double-Entry Accounting Engine (see the
-- Sprint 4.3A app.js scaffold: ACCOUNTING_RULES / buildJournalEntries /
-- isBalancedJournal) will eventually post Journal Entries against.
--
-- finance_chart_of_accounts is DELIBERATELY separate from finance_accounts:
--   - finance_accounts   = operational bank/cash accounts (business_bank,
--     personal_account, partner_account, cash) used today by the Finance
--     Dashboard for real cash balances (getAccountBalance()).
--   - finance_chart_of_accounts = the broader accounting classification
--     (asset/liability/equity/revenue/expense) that a real ledger needs,
--     which finance_accounts' account_type was never designed to express.
-- This migration does not touch finance_accounts and does not change any
-- existing balance, formula, or UI.
-- ============================================================

CREATE TABLE IF NOT EXISTS finance_chart_of_accounts (
  id                         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account_code               text NOT NULL UNIQUE,
  account_name               text NOT NULL,
  account_type               text NOT NULL CHECK (account_type IN ('asset', 'liability', 'equity', 'revenue', 'expense')),
  account_subtype            text NULL,
  normal_balance             text NOT NULL CHECK (normal_balance IN ('debit', 'credit')),
  parent_account_id          bigint NULL REFERENCES finance_chart_of_accounts(id),
  linked_finance_account_id  bigint NULL REFERENCES finance_accounts(id),
  is_active                  boolean NOT NULL DEFAULT true,
  description                text NULL,
  created_at                 timestamptz NOT NULL DEFAULT now(),
  updated_at                 timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS finance_coa_account_code_idx   ON finance_chart_of_accounts(account_code);
CREATE INDEX IF NOT EXISTS finance_coa_account_type_idx   ON finance_chart_of_accounts(account_type);
CREATE INDEX IF NOT EXISTS finance_coa_is_active_idx       ON finance_chart_of_accounts(is_active);
CREATE INDEX IF NOT EXISTS finance_coa_parent_account_idx  ON finance_chart_of_accounts(parent_account_id);
CREATE INDEX IF NOT EXISTS finance_coa_linked_account_idx  ON finance_chart_of_accounts(linked_finance_account_id);

-- Seed: minimal flat starter Chart of Accounts. No parent_account_id and no
-- linked_finance_account_id yet — see Sprint 4.3B report for why linking to
-- finance_accounts is deferred (a clean rollup from operational accounts to
-- COA lines needs its own design, e.g. multiple finance_accounts could roll
-- into one "Cash and Bank" line). ON CONFLICT on the unique account_code
-- keeps this safe to re-run and safe to extend with more seed rows later.
INSERT INTO finance_chart_of_accounts (account_code, account_name, account_type, normal_balance) VALUES
  -- Assets (normal balance: debit)
  ('1000', 'Cash and Bank',            'asset',     'debit'),
  ('1100', 'Accounts Receivable',      'asset',     'debit'),
  ('1200', 'Client Funds Held Asset',  'asset',     'debit'),
  -- Liabilities (normal balance: credit)
  ('2000', 'Accounts Payable',         'liability', 'credit'),
  ('2100', 'Client Funds Liability',   'liability', 'credit'),
  -- Equity (normal balance: credit)
  -- Note: Partner Drawings is conventionally a contra-equity account with a
  -- natural debit balance. It is seeded as 'credit' here to match this
  -- sprint's explicit "Equity: credit" starter rule (flat structure, no
  -- contra-account modeling yet) — flagged for revisit once Journal Posting
  -- is designed.
  ('3000', 'Owner Equity',             'equity',    'credit'),
  ('3100', 'Capital Contributions',    'equity',    'credit'),
  ('3200', 'Partner Drawings',         'equity',    'credit'),
  -- Revenue (normal balance: credit)
  ('4000', 'Service Revenue',          'revenue',   'credit'),
  -- Expenses (normal balance: debit)
  ('5000', 'Operating Expenses',       'expense',   'debit'),
  ('5100', 'Software Subscriptions',   'expense',   'debit'),
  ('5200', 'Salaries Expense',         'expense',   'debit'),
  ('5300', 'Utilities Expense',        'expense',   'debit')
ON CONFLICT (account_code) DO NOTHING;

-- Force PostgREST to reload its schema cache immediately.
NOTIFY pgrst, 'reload schema';
