-- ============================================================
-- Tgora OS — Finance Fixed Costs Module (Sprint 4.1B)
-- Run AFTER finance_settings_migration.sql (Sprint 4.1A)
-- Safe to run multiple times (idempotent).
--
-- Purpose: promote Fixed Costs from a finance_settings jsonb array into a
-- proper Finance Core entity, so line items can eventually be added/edited
-- individually. This migration only creates the table and seeds the
-- values currently in finance_settings ('fixed_costs') / the app.js
-- fallback — it does not change any business rule.
-- ============================================================

CREATE TABLE IF NOT EXISTS finance_fixed_costs (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cost_name  text NOT NULL,
  amount     numeric NOT NULL DEFAULT 0,
  category   text NULL,
  frequency  text NOT NULL DEFAULT 'monthly',
  start_date date NULL,
  end_date   date NULL,
  is_active  boolean NOT NULL DEFAULT true,
  notes      text NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS finance_fixed_costs_active_idx    ON finance_fixed_costs(is_active);
CREATE INDEX IF NOT EXISTS finance_fixed_costs_category_idx  ON finance_fixed_costs(category);
CREATE INDEX IF NOT EXISTS finance_fixed_costs_frequency_idx ON finance_fixed_costs(frequency);

-- Seed: current fixed costs (matches finance_settings 'fixed_costs' /
-- FINANCE_FIXED_COSTS_DEFAULT in app.js). Only seeds if the table is empty,
-- so re-running this migration won't duplicate rows or clobber edits made
-- once a Fixed Costs UI exists.
INSERT INTO finance_fixed_costs (cost_name, amount, frequency)
SELECT * FROM (VALUES
  ('Salaries',             52000::numeric, 'monthly'),
  ('Adobe',                1600::numeric,  'monthly'),
  ('Google Workspace',     1100::numeric,  'monthly'),
  ('ChatGPT',              1400::numeric,  'monthly'),
  ('Internet / Utilities', 1200::numeric,  'monthly'),
  ('Miscellaneous',        3000::numeric,  'monthly')
) AS seed(cost_name, amount, frequency)
WHERE NOT EXISTS (SELECT 1 FROM finance_fixed_costs);

-- Force PostgREST to reload its schema cache immediately.
NOTIFY pgrst, 'reload schema';
