-- ============================================================
-- Tgora OS — Project Commercial Terms & Payment Schedule
-- Schema Foundation (Sprint Project Commercial A)
-- Safe to run multiple times (idempotent).
--
-- Context: Approved business model is
--   Deal -> Project -> Commercial Terms -> Payment Schedule Items
--     -> (future) Finance Forecasts -> (future) Finance Transactions
--     -> Accounting
--
-- Payment Schedule Item is the reconciliation anchor: future Finance
-- Forecasts and Finance Transactions will link back to a specific
-- project_payment_schedule_items row rather than assuming a 1:1
-- Forecast <-> Transaction relationship. That linkage (forecast
-- generation, out-of-sync detection) is an explicit future Admin-action
-- sprint and is deliberately NOT built here — see the columns this
-- migration intentionally omits below.
--
-- This migration is SCHEMA FOUNDATION ONLY. It does NOT:
--   - add any UI (no Project Details cards, no Payment Schedule UI)
--   - touch finance_forecasts, finance_transactions, finance_accounts,
--     finance_chart_of_accounts, or any other finance_*/accounting table
--   - create Finance Forecasts, Finance Transactions, or Accounting
--     Journal Entries from Commercial Terms or Payment Schedule Items
--   - add collected_amount, outstanding_amount, status, forecast
--     linkage, or transaction linkage columns to
--     project_payment_schedule_items — those belong to later sprints
--     once Forecast integration is explicitly approved
--   - add revenue_value, client_funds_value, or scheduled_value to
--     project_commercial_terms — those are derived (SUM) from
--     project_payment_schedule_items, not stored
--   - rename, remove, or alter any existing table/column
--   - add RLS policies (see "RLS decision" in the sprint report — no
--     existing table in this codebase has a verified, working RLS
--     policy to model from, and this migration does not guess one)
-- ============================================================

-- ----------------------------------------------------------------
-- 1. project_commercial_terms
--    One commercial contract/terms record per Project.
-- ----------------------------------------------------------------
CREATE TABLE IF NOT EXISTS project_commercial_terms (
  id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id     bigint NOT NULL REFERENCES projects(id),
  contract_value numeric(15,2) NOT NULL CHECK (contract_value >= 0),
  currency       text NOT NULL DEFAULT 'EGP' CHECK (btrim(currency) <> ''),
  notes          text NULL,
  created_by     uuid NULL,
  created_at     timestamptz NOT NULL DEFAULT now(),
  updated_at     timestamptz NOT NULL DEFAULT now()
);

-- One Project -> at most one Commercial Terms record.
CREATE UNIQUE INDEX IF NOT EXISTS project_commercial_terms_project_id_key
  ON project_commercial_terms(project_id);

-- ----------------------------------------------------------------
-- 2. project_payment_schedule_items
--    Installments/payment schedule rows under a Project's Commercial
--    Terms record. total_amount is split into revenue_amount (Tgora
--    revenue) and client_funds_amount (pass-through client funds, e.g.
--    ad spend held on the client's behalf) — the two must always sum
--    to total_amount so Commercial Summary's Revenue Value and Client
--    Funds Value can be derived by SUM() without reconciliation logic.
-- ----------------------------------------------------------------
CREATE TABLE IF NOT EXISTS project_payment_schedule_items (
  id                   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  commercial_terms_id  bigint NOT NULL REFERENCES project_commercial_terms(id),
  label                text NULL,
  due_date             date NOT NULL,
  total_amount         numeric(15,2) NOT NULL CHECK (total_amount >= 0),
  revenue_amount       numeric(15,2) NOT NULL DEFAULT 0 CHECK (revenue_amount >= 0),
  client_funds_amount  numeric(15,2) NOT NULL DEFAULT 0 CHECK (client_funds_amount >= 0),
  client_funds_purpose text NULL,
  is_cancelled         boolean NOT NULL DEFAULT false,
  created_by           uuid NULL,
  created_at           timestamptz NOT NULL DEFAULT now(),
  updated_at           timestamptz NOT NULL DEFAULT now(),
  CHECK (total_amount = revenue_amount + client_funds_amount)
);

CREATE INDEX IF NOT EXISTS project_payment_schedule_items_terms_idx
  ON project_payment_schedule_items(commercial_terms_id);
CREATE INDEX IF NOT EXISTS project_payment_schedule_items_due_date_idx
  ON project_payment_schedule_items(due_date);

-- Force PostgREST to reload its schema cache immediately.
NOTIFY pgrst, 'reload schema';

-- ============================================================
-- Verification (run manually in the Supabase SQL editor after applying):
--
-- -- Confirm both tables exist with expected columns:
-- SELECT table_name, column_name, data_type, is_nullable, column_default
-- FROM information_schema.columns
-- WHERE table_name IN ('project_commercial_terms', 'project_payment_schedule_items')
-- ORDER BY table_name, ordinal_position;
--
-- -- Confirm FKs are live:
-- SELECT conname, conrelid::regclass AS table_name, confrelid::regclass AS references_table
-- FROM pg_constraint
-- WHERE conrelid IN ('project_commercial_terms'::regclass, 'project_payment_schedule_items'::regclass)
--   AND contype = 'f';
--
-- -- Confirm CHECK constraints are live:
-- SELECT conname, conrelid::regclass AS table_name, pg_get_constraintdef(oid) AS definition
-- FROM pg_constraint
-- WHERE conrelid IN ('project_commercial_terms'::regclass, 'project_payment_schedule_items'::regclass)
--   AND contype = 'c';
--
-- -- Confirm indexes:
-- SELECT indexname, indexdef FROM pg_indexes
-- WHERE tablename IN ('project_commercial_terms', 'project_payment_schedule_items');
-- ============================================================
