-- ============================================================
-- Tgora OS — Finance Forecast Linkage Schema Foundation
-- (Sprint Project Commercial C1)
-- Run AFTER project_commercial_terms_schema_migration.sql (Commercial A)
-- and finance_migration_4_1a.sql (Finance 4.1A — is_deleted/is_archived
-- lifecycle on finance_forecasts).
-- Safe to run multiple times (idempotent).
--
-- Context: Approved architecture (Project Commercial C report) is
--   Payment Schedule Item -> 0-2 generated Finance Forecast rows
--     (revenue component, client funds component)
--     -> (future) Finance Transaction(s)
--     -> Accounting
--
-- This migration is SCHEMA FOUNDATION ONLY — additive linkage columns
-- on finance_forecasts so a future sprint (C2) can generate forecasts
-- from a project_payment_schedule_items row. It does NOT:
--   - implement forecast generation (no JS engine, no button, no action)
--   - implement any UI (no Generate Forecast, no Out of Sync badge, no
--     Source Cancelled badge, no Review Differences / Update Forecast
--     from Schedule UX — all deferred to C2/C3 per the approved report)
--   - implement the Forecasted Client Funds KPI (deferred to C3)
--   - touch project_payment_schedule_items or project_commercial_terms
--     in any way
--   - touch finance_transactions in any way (no payment_schedule_item_id
--     or forecast_id column added there — that is future, unapproved
--     scope per the Project Commercial C report's "Actual Layer")
--   - modify convertForecastToTransaction() or any other app.js logic
--   - add a real FK from finance_forecasts.project_ref_id to projects(id)
--     — investigated and deliberately deferred, see "Project Linkage
--     Decision" below
--   - add RLS policies — no table in this codebase has a verified,
--     working RLS policy to model from (confirmed again in this sprint's
--     investigation: zero CREATE POLICY / ENABLE ROW LEVEL SECURITY
--     statements exist in any tracked migration), and this migration
--     does not introduce an isolated policy for just these columns
--   - backfill any existing finance_forecasts row — every new column is
--     nullable (or defaults to false) and every existing row simply gets
--     the "not generated from schedule" values below
--
-- Investigation findings this design is based on (repository inspection,
-- not assumption):
--   - finance_forecasts.id is bigserial; project_payment_schedule_items.id
--     is `bigint GENERATED BY DEFAULT AS IDENTITY` — both resolve to
--     bigint, so a bigint FK column is type-compatible with no cast.
--   - finance_forecasts.is_deleted and .status are both NOT NULL with
--     defaults (is_deleted defaults false, status defaults 'expected')
--     — confirmed in finance_migration_4_1.sql / finance_migration_4_1a.sql
--     — so a duplicate-prevention predicate never has to special-case a
--     NULL is_deleted or NULL status.
--   - finance_forecasts.status values in actual use (UI select +
--     FINANCE_FORECAST_STATUS_LABELS in app.js): expected, committed,
--     received, cancelled (there is no DB CHECK constraint on this
--     column today — enforcement is JS-layer only, unchanged by this
--     migration).
--   - archiveFinanceForecast()/restoreFinanceForecast() in app.js treat
--     is_archived as an independent visibility toggle, not a business-
--     state change: an archived forecast is still real, still restorable,
--     and is never implicitly treated as invalid/superseded elsewhere in
--     the codebase (same pattern as CRM contacts/deals/leads archive).
--     Per the approved decision rule, archive is therefore NOT treated
--     as "non-active" for duplicate prevention below — only is_deleted
--     and status = 'cancelled' do that.
--   - finance_forecasts.created_by / finance_transactions.deleted_by /
--     archived_by are all `uuid NULL REFERENCES auth.users(id)` — the
--     Finance-module convention for actor columns. generated_by below
--     follows that same convention (project_commercial_terms/
--     project_payment_schedule_items.created_by, by contrast, is a bare
--     `uuid NULL` with no FK — that is the Project-module convention;
--     this migration follows the Finance-module convention since the
--     column lives on finance_forecasts).
--   - finance_forecasts.project_ref_id is `bigint NULL`, added in
--     finance_migration_4_1.sql, with NO FK constraint. A repository-wide
--     search found zero reads or writes of this column anywhere in
--     app.js or index.html — it has never been populated by any
--     application code path. However, this migration has no access to
--     the live Supabase database, so it cannot confirm every existing
--     row's project_ref_id is NULL or points at a valid projects.id (a
--     value could in principle have been written by hand outside the
--     app). Per the approved decision rule ("do NOT add the FK if live-
--     data validity cannot be proven from repository inspection"), the
--     FK is deferred — see verification query 6 below, which must be
--     run and confirmed empty before any future hardening migration
--     adds `REFERENCES projects(id)` to this column.
-- ============================================================

-- 1. Extend finance_forecasts with schedule-linkage columns.
ALTER TABLE finance_forecasts
  ADD COLUMN IF NOT EXISTS payment_schedule_item_id  bigint NULL REFERENCES project_payment_schedule_items(id),
  ADD COLUMN IF NOT EXISTS forecast_component        text NULL,
  ADD COLUMN IF NOT EXISTS generated_from_schedule    boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS source_snapshot_amount     numeric(15,2) NULL,
  ADD COLUMN IF NOT EXISTS source_snapshot_due_date   date NULL,
  ADD COLUMN IF NOT EXISTS source_snapshot_updated_at timestamptz NULL,
  ADD COLUMN IF NOT EXISTS generated_by               uuid NULL REFERENCES auth.users(id);

-- 2. forecast_component enum-style guard. NULL remains allowed (every
--    manually-created forecast, past and future, has no component).
--    No NOT VALID needed here — unlike crm_leads_status_check (Sprint
--    CRM-4.5D Fix Pass), this is a brand-new column being added in this
--    same migration, so every existing row is guaranteed to receive NULL
--    for it and trivially satisfies the constraint; there is no unknown
--    live-data risk to guard against.
ALTER TABLE finance_forecasts DROP CONSTRAINT IF EXISTS finance_forecasts_component_check;
ALTER TABLE finance_forecasts ADD CONSTRAINT finance_forecasts_component_check
  CHECK (forecast_component IS NULL OR forecast_component IN ('revenue', 'client_funds'));

-- 3. Lookup index — "does this Payment Item have any generated forecasts".
CREATE INDEX IF NOT EXISTS finance_forecasts_payment_schedule_item_idx
  ON finance_forecasts(payment_schedule_item_id);

-- 4. Duplicate-prevention: at most one active generated forecast per
--    (payment_schedule_item_id, forecast_component). Scoped to
--    generated_from_schedule = true so it never constrains manually
--    created forecasts (which always have payment_schedule_item_id
--    NULL in this sprint, but the predicate is explicit rather than
--    relying on that alone). Excludes is_deleted and status = 'cancelled'
--    rows so a cancelled/deleted generated forecast can be regenerated —
--    per the investigation above, is_archived is deliberately NOT part
--    of this predicate, since archive does not mean "non-active" for any
--    other Finance record in this codebase.
CREATE UNIQUE INDEX IF NOT EXISTS finance_forecasts_schedule_component_unique_idx
  ON finance_forecasts (payment_schedule_item_id, forecast_component)
  WHERE generated_from_schedule = true
    AND is_deleted = false
    AND status <> 'cancelled';

-- Force PostgREST to reload its schema cache immediately.
NOTIFY pgrst, 'reload schema';

-- ============================================================
-- Verification (run manually in the Supabase SQL editor after applying):
--
-- -- 1. Confirm all 7 new columns exist with expected types/defaults:
-- SELECT column_name, data_type, is_nullable, column_default
-- FROM information_schema.columns
-- WHERE table_name = 'finance_forecasts'
--   AND column_name IN (
--     'payment_schedule_item_id', 'forecast_component',
--     'generated_from_schedule', 'source_snapshot_amount',
--     'source_snapshot_due_date', 'source_snapshot_updated_at',
--     'generated_by'
--   )
-- ORDER BY column_name;
--
-- -- 2. Confirm the payment_schedule_item_id FK and generated_by FK are live:
-- SELECT conname, conrelid::regclass AS table_name, confrelid::regclass AS references_table
-- FROM pg_constraint
-- WHERE conrelid = 'finance_forecasts'::regclass AND contype = 'f'
--   AND (conname LIKE '%payment_schedule_item%' OR conname LIKE '%generated_by%');
--
-- -- 3. Confirm the forecast_component CHECK constraint is live:
-- SELECT conname, pg_get_constraintdef(oid) AS definition
-- FROM pg_constraint
-- WHERE conrelid = 'finance_forecasts'::regclass
--   AND conname = 'finance_forecasts_component_check';
--
-- -- 4. Confirm both new indexes exist:
-- SELECT indexname, indexdef FROM pg_indexes
-- WHERE tablename = 'finance_forecasts'
--   AND indexname IN (
--     'finance_forecasts_payment_schedule_item_idx',
--     'finance_forecasts_schedule_component_unique_idx'
--   );
--
-- -- 5. Confirm every existing forecast row is untouched / backward
-- --    compatible (should return the full existing row count, all with
-- --    the "not generated from schedule" defaults):
-- SELECT count(*) AS total_forecasts,
--        count(*) FILTER (WHERE payment_schedule_item_id IS NULL)  AS null_link,
--        count(*) FILTER (WHERE forecast_component IS NULL)        AS null_component,
--        count(*) FILTER (WHERE generated_from_schedule = false)   AS not_generated
-- FROM finance_forecasts;
-- -- Expect null_link = null_component = not_generated = total_forecasts.
--
-- -- 6. Run BEFORE any future migration adds a real FK from
-- --    finance_forecasts.project_ref_id to projects(id) — must return
-- --    zero rows for that hardening migration to be safe:
-- SELECT id, project_ref_id
-- FROM finance_forecasts
-- WHERE project_ref_id IS NOT NULL
--   AND project_ref_id NOT IN (SELECT id FROM projects);
-- ============================================================
